### ISSUE TITLE
页面按钮问题bug

### ISSUE THREAD

**Issue by aiesst** [nutbox-dao/peanut-interface-v2#8]
1、当连接钱包的时候，钱包不授予连接的时候，按钮还是一直处于加载状态。比如PNUT-TRX LP授权按钮，一直加载状态。
2、当加载状态的时候，切换左边菜单时，按钮会闪烁。
3、点赞菜单下的转账按钮过大，不美观。
![图1](https://www.hualigs.cn/image/604b2d39682b5.jpg)
![图2](https://www.hualigs.cn/image/604b2d3959046.jpg)

地址：TEFvAbSH6rpxWd2htDdsYcDHWQabZbXC16

**Comment by aiesst** [comment]
这些问题希望得到改善，不然会很影响用户体验

**Comment by aiesst** [comment]
google浏览器

**Comment by tolak** [comment]
@terryyyyyy Pls have a look

**Comment by terryyyyyy** [comment]
1.Because of the network of tron is too late recently. We always can't get the data back soon in a long term. And we can't do some important operation when the critical data isn't back. We are try to find other solutions for this problem. But the problem doesn't exist all the time. You can try it after a half day.
2.What kind of spling of that？ Could you provide detail operations that can reappear this issue.
3.Thanks for your advice. I'll tolk about this one to our designer.

**Comment by terryyyyyy** [comment]
@Gump-II Now we have fixed this issue.Could check it and close this issue?

**Comment by tolak** [comment]
Already fixed, close this issue.
